FROM rocm/pytorch:rocm6.4.2_ubuntu22.04_py3.10_pytorch_release_2.6.0

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl gnupg \
  ca-certificates \
  sudo libelf1 libnuma-dev libssl-dev \
  pkg-config \
  build-essential \
  git \
  patchelf \
  file less \
  ninja-build \
  clang \
  libfile-which-perl liburi-perl cmake && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip twine auditwheel
