FROM rocm/vllm-dev:base 

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl gnupg \
  ca-certificates \
  sudo libelf1 libnuma-dev libssl-dev \
  pkg-config \
  build-essential \
  git \
  patchelf \
  file less \
  ninja-build \
  clang \
  libfile-which-perl liburi-perl && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip twine auditwheel