#pragma once

#include "gemm/rocm/quantization/gemm.h"

namespace causalflow::petit::rocm::quantization::fp4 {

namespace detail {

static constexpr SolutionId SolIdMNK(int features, MatmulPipeline pipeline,
                                     MatmulMfmaType mfma_type, unsigned tile_m,
                                     unsigned tile_n, unsigned tile_k,
                                     unsigned partition_m, unsigned partition_n,
                                     unsigned partition_k) {
    return SolutionId::MultiStage(pipeline, (MatmulFeatures)features,
                                  MatmulElementB::kMatmulTypeBFp4, mfma_type,
                                  tile_m, tile_n, tile_k,
                                  MatmulWarpPartition::kMatmulWarpPartition_NK,
                                  partition_m, partition_n, partition_k);
}

static constexpr SolutionId SolId(int features, MatmulPipeline pipeline,
                                  MatmulMfmaType mfma_type, unsigned tile_m,
                                  unsigned tile_n, unsigned tile_k) {
    return SolIdMNK(features, pipeline, mfma_type, tile_m, tile_n, tile_k, 1,
                    tile_n, 4 / tile_n);
}

static constexpr SolutionId kAvailableSolutions[] = {
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_1,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 1, 32),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_1,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 1, 32),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 4, 32, 1, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 32, 1, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 32, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 4, 32, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 32, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 32, 2, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 4, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 2, 16, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 8, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 4, 16, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 1, 16, 2, 1, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 1, 32, 2, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 3, 16, 2, 1, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_2,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_2,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 1, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 1, 16, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 2, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 3, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 3, 16, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 6, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 10, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 6, 6, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 8, 4, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 8, 4, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 8, 5, 8, 4, 1, 1),

    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_1,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 1, 32),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_1,
          MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 1, 32),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 4, 32, 1, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 32, 1, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 32, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 4, 32, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 32, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 32, 2, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 4, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 2, 16, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 8, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 1, 4, 16, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 1, 16, 2, 1, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 1, 32, 2, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 3, 16, 2, 1, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_2,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 2, 4, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_2,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 1, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 1, 16, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 2, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 3, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 3, 16, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 6, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 4, 10, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 6, 6, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 8, 4, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 8, 4, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeFp16, 8, 5, 8, 4, 1, 1),

    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_1,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 1, 32),
    SolId(MatmulFeatures::kMatmulFeatures_Grid,
          MatmulPipeline::kMatmulPipeline_1,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 1, 32),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 4, 32, 1, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 32, 1, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 32, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 4, 32, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 32, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 32, 2, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 4, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 2, 16, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 8, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 4, 16, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 1, 16, 2, 1, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 1, 32, 2, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 3, 16, 2, 1, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_2,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_2,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 1, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 1, 16, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 2, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 3, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 3, 16, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 6, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 10, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 6, 6, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 8, 4, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 8, 4, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 8, 5, 8, 4, 1, 1),

    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 4, 8),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_1,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 2, 16),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_2,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 1, 32),
    SolId(MatmulFeatures::kMatmulFeatures_Grid |
              MatmulFeatures::kMatmulFeatures_HighPrecision,
          MatmulPipeline::kMatmulPipeline_1,
          MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 1, 32),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 4, 32, 1, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 32, 1, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 32, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 4, 32, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 32, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 32, 2, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 4, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 2, 16, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 8, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 1, 4, 16, 1, 2, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 1, 16, 2, 1, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 1, 32, 2, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 3, 16, 2, 1, 2),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_2,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 2, 4, 8, 1, 4, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_2,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 1, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 1, 16, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 2, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 3, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 3, 16, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 6, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 4, 10, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 6, 6, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 8, 4, 8, 2, 2, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 8, 4, 8, 4, 1, 1),
    SolIdMNK(MatmulFeatures::kMatmulFeatures_Grid |
                 MatmulFeatures::kMatmulFeatures_HighPrecision,
             MatmulPipeline::kMatmulPipeline_1,
             MatmulMfmaType::kMatmulMfmaTypeBf16, 8, 5, 8, 4, 1, 1),

};

} // namespace detail
} // namespace causalflow::petit::rocm::quantization::fp4